# Generated by Django 4.2.7 on 2024-12-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodentry',
            name='activities',
            field=models.CharField(choices=[('Work', 'Work'), ('Family', 'Family'), ('Friends', 'Friends'), ('Exercise', 'Exercise'), ('Hobbies', 'Hobbies'), ('Rest', 'Rest'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='energy_level',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='sleep_hours',
            field=models.CharField(choices=[('0-4', 'Less than 4 hours'), ('4-6', '4-6 hours'), ('6-8', '6-8 hours'), ('8+', 'More than 8 hours')], default='6-8', max_length=10),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='stress_level',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='weather',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
