# Generated by Django 4.2.7 on 2024-12-14 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0002_moodentry_activities_moodentry_energy_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moodentry',
            name='location',
        ),
        migrations.RemoveField(
            model_name='moodentry',
            name='weather',
        ),
    ]
