# Generated by Django 4.2.7 on 2024-12-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0003_remove_moodentry_location_remove_moodentry_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodentry',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
