# Generated by Django 4.2.7 on 2024-12-14 15:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0004_moodentry_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodentry',
            name='local_timezone',
            field=models.CharField(default=django.utils.timezone.get_current_timezone_name, max_length=50),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
