# Generated by Django 4.2.7 on 2025-01-09 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_alter_profile_user_alter_profile_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='BPRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('systolic', models.PositiveIntegerField()),
                ('diastolic', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bp_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
